# Generated by Django 5.1.3 on 2024-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customconteiner",
            options={"verbose_name": "контейнер", "verbose_name_plural": "Контейнеры"},
        ),
        migrations.AlterField(
            model_name="customconteiner",
            name="text",
            field=models.CharField(max_length=10, verbose_name="Текстовое сообщение"),
        ),
        migrations.AlterField(
            model_name="customconteiner",
            name="volume",
            field=models.IntegerField(verbose_name="Объем"),
        ),
    ]
