# Generated by Django 5.1.3 on 2024-11-30 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="capacity",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Capacity должно быть больше или равно 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        1000000, message="Capacity не должно превышать 1000000"
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Text может содержать только буквы, цифры или разрешённые символы.",
                        regex="^[a-zA-Z0-9!@#$%^&*()\\-_+=\\[\\]{};:,.<>?/|\\\\~`]+$",
                    )
                ],
            ),
        ),
    ]
