
volumes:
  pg_data:
  static:
  media:

services:
  termet:
    image: ${DOCKER_USERNAME}/termet
    env_file: .env
    environment:
      - TZ=Europe/Minsk
    volumes:
      - static:/backend_static


  gateway:
    image: ${DOCKER_USERNAME}/termet_gateway
    volumes:
      - static:/staticfiles/
    ports:
      - 9000:80
    environment:
      - TZ=Europe/Minsk
